/*
 * Copyright (c) 2011-2014 Graham Edgecombe <graham@grahamedgecombe.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef ARC_MM_ALIGN_H
#define ARC_MM_ALIGN_H

#define PAGE_ALIGN(x) (((x) + 0xFFF) & 0xFFFFFFFFFFFFF000)
#define PAGE_ALIGN_REVERSE(x) ((x) & 0xFFFFFFFFFFFFF000)

#define PAGE_ALIGN_2M(x) (((x) + 0x1FFFFF) & 0xFFFFFFFFFFE00000)
#define PAGE_ALIGN_REVERSE_2M(x) ((x) & 0xFFFFFFFFFFE00000)

#define PAGE_ALIGN_1G(x) (((x) + 0x3FFFFFFF) & 0xFFFFFFFFC0000000)
#define PAGE_ALIGN_REVERSE_1G(x) ((x) & 0xFFFFFFFFC0000000)

#endif
