/*
 * Copyright (c) 2011-2012 Graham Edgecombe <graham@grahamedgecombe.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef ARC_INTR_IOAPIC_H
#define ARC_INTR_IOAPIC_H

#define IOAPIC_ID       0x00
#define IOAPIC_VER      0x01
#define IOAPIC_ARB      0x02
#define IOAPIC_REDTBL0  0x10
#define IOAPIC_REDTBL1  0x12
#define IOAPIC_REDTBL2  0x14
#define IOAPIC_REDTBL3  0x16
#define IOAPIC_REDTBL4  0x18
#define IOAPIC_REDTBL5  0x1A
#define IOAPIC_REDTBL6  0x1C
#define IOAPIC_REDTBL7  0x1E
#define IOAPIC_REDTBL8  0x20
#define IOAPIC_REDTBL9  0x22
#define IOAPIC_REDTBL10 0x24
#define IOAPIC_REDTBL11 0x26
#define IOAPIC_REDTBL12 0x28
#define IOAPIC_REDTBL13 0x2A
#define IOAPIC_REDTBL14 0x2C
#define IOAPIC_REDTBL15 0x2E
#define IOAPIC_REDTBL16 0x30
#define IOAPIC_REDTBL17 0x32
#define IOAPIC_REDTBL18 0x34
#define IOAPIC_REDTBL19 0x36
#define IOAPIC_REDTBL20 0x38
#define IOAPIC_REDTBL21 0x3A
#define IOAPIC_REDTBL22 0x3C
#define IOAPIC_REDTBL23 0x3E

#endif

